### ISSUE TITLE
Allow annotations to be added to package-info.java

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb2-annotate-plugin#1]
Continued from https://github.com/highsource/annox/issues/1.

**Comment by nocivus** [comment]
The annotatePackage tag (which i assume is a shortcut for <annotate target="package"> does not work in 1.0.1.

**Comment by highsource** [comment]
@nocivus Confirmed, reopening.

**Comment by hafizullah** [comment]
Have there been any progress on this fix please? Desperately need this feature :)

**Comment by highsource** [comment]
Both `annotate:annotate` with `target="package"` and `annotate:annotatePackage` work.
