### ISSUE TITLE
Include license header in source files

### ISSUE THREAD

**Issue by puntogil** [highsource/jaxb2-annotate-plugin#12]
Hi
Found 5 files have "unknown" license.
jaxb2-annotate-plugin-1.0.1/plugin/src/main/java/org/jvnet/jaxb2_commons/plugin/annotate/AnnotatePlugin.java
jaxb2-annotate-plugin-1.0.1/plugin/src/main/java/org/jvnet/jaxb2_commons/plugin/annotate/AnnotatingArrayValueVisitor.java
jaxb2-annotate-plugin-1.0.1/plugin/src/main/java/org/jvnet/jaxb2_commons/plugin/annotate/AnnotatingSingleValueVisitor.java
jaxb2-annotate-plugin-1.0.1/plugin/src/main/java/org/jvnet/jaxb2_commons/plugin/annotate/AnnotatingVisitor.java
jaxb2-annotate-plugin-1.0.1/plugin/src/main/java/org/jvnet/jaxb2_commons/plugin/annotate/Annotator.java
Please, add license header in the above files
See https://bugzilla.redhat.com/show_bug.cgi?id=1249047#c1 for details.
Thanks in advance
Regards

**Comment by highsource** [comment]
Ahm. I did not knew BSD 2-clause has to be in each source file. Is it really so?

I actually don't mind it, but, frankly, seems an absolute overkill to me. Probably the `maven-license plugin` would be handy here. But it's effort...

Would you consider helping by making a PR which would integrate the `maven-license-plugin` into the build? Then we'll have solved it once and for all and I could replicate the solution in other projects as well.
