### ISSUE TITLE
Does not allow gson SerializedName to bindings.xjb

### ISSUE THREAD

**Issue by jiechu** [highsource/jaxb2-annotate-plugin#13]
For Exmple, the xsd is as:
`<xs:complexType name="property">`
       ` <xs:attribute name="key" type="xs:string" use="required"/>`
       ` <xs:attribute name="value" type="xs:string" use="required"/>`
`</xs:complexType>`
And the bindings.xjb is as:
`<jxb:bindings node="xs:complexType[@name='property']">`
            `<annox:annotate>`
                `<annox:annotate annox:class="javax.xml.bind.annotation.XmlRootElement" name="property"/>`
            `</annox:annotate>`
        `</jxb:bindings>`
        `<jxb:bindings node="xs:complexType[@name='property']/xs:attribute[@name='key']">`
            `<annox:annotate target="field">@com.google.gson.annotations.SerializedName("@key")</annox:annotate>`
        `</jxb:bindings>`
        `<jxb:bindings node="xs:complexType[@name='property']/xs:attribute[@name='value']">`
           ` <annox:annotate target="field">@com.google.gson.annotations.SerializedName("@value")</annox:annotate>`
       `</jxb:bindings>`
The pom.xml is as:
`<dependency>`
    `<groupId>com.google.code.gson</groupId>`
    `<artifactId>gson</artifactId>`
 `</dependency>`
`<build>`
        `<plugins>`
           `<plugin>`
                `<groupId>org.jvnet.jaxb2.maven2</groupId>`
                `<artifactId>maven-jaxb2-plugin</artifactId>`
                `<version>${maven_jaxb2_plugin_version}</version>`
`... `
`</plugin>`
`...`
`</build>`
Then I got an error: 
Caused by: java.lang.ClassNotFoundException: com.google.gson.annotations.SerializedName

Could you please help how to resolve it? Or it is an issue for the plugin?

**Comment by highsource** [comment]
You have to add `com.google.code.gson:gson` to the `maven-jaxb2-plugin` classpath via `plugin/configuration/plugins/plugin`. Please refer to [this documentation](https://github.com/highsource/jaxb2-annotate-plugin#using-jaxb2-annotate-plugin-with-maven).

**Comment by jiechu** [comment]
resolved
