### ISSUE TITLE
The argument does not make effect with plugin

### ISSUE THREAD

**Issue by jiechu** [highsource/jaxb2-annotate-plugin#14]
When work with plugin: 
`<plugin>`
`<groupId>com.github.jaxb-xew-plugin</groupId>`
`<artifactId>jaxb-xew-plugin</artifactId>`
`<version>${jaxb_xew_plugin_version}</version>`
`</plugin>`
There is package-info.java generated event if use -npa or <packageLevelAnnotations>false</packageLevelAnnotations>

**Comment by highsource** [comment]
And how is this relevant to `jaxb2-annotate-plugin`?
