### ISSUE TITLE
Use jaxb:class and annox:annotate together in jaxb2-maven-plugin

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb2-annotate-plugin#16]
See http://stackoverflow.com/questions/32257883/use-jaxbclass-and-annoxannotate-together-in-jaxb2-maven-plugin

@mundodojava Here's an issue.

**Comment by highsource** [comment]
Reproduced.

**Comment by skittle134** [comment]
I have a similar problem related to this issue: 
[https://stackoverflow.com/questions/49299912/manipulate-jaxb-to-create-idref-elements-instead-of-jaxbelement](url)
My problem could be resolved by fixing this bug.
The project setup is the same as the original reported issue, but if new code-samples are needed, i can provide them.

**Comment by highsource** [comment]
Ok, the problem is that XJC attaches this customization to the `CClassRef` (`jaxb:class`) as well as to the property.

The solution should be to simply mark the customization on `CClassRef` as acknowledged.
WIP.

**Comment by highsource** [comment]
Fixed on the `issue-16` branch. Please check out, build and try out.

**Comment by skittle134** [comment]
Sorry for the Delay.
I've successfully tested your change. Now the plugin is working as desired.
Thank you very much!
