### ISSUE TITLE
Annotating a simpleContent 

### ISSUE THREAD

**Issue by eyce9000** [highsource/jaxb2-annotate-plugin#24]
I am trying to annotate a field that is normally annotated by xjc with `@XmlValue` in order to add a CDATA annotation to it.

How do I set up my binding to do this, or is it possible?

Binding:

``` xml
<bindings node="//xs:complexType[@name='ActionScript']">
  <annox:annotate>
    <annox:annotate annox:class="org.eclipse.persistence.oxm.annotations.XmlCDATA"/>
  </annox:annotate>
</bindings>
```

Type in question:

``` xml
<xs:complexType name="ActionScript">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="MIMEType" type="xs:normalizedString" default="application/x-Fixlet-Windows-Shell" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
```

**Comment by highsource** [comment]
Hi,

this appeared to be more complex than I thought. I did not manage to attach customizations to the simple content-derived property with standard XJC means. So I wrote the `customizations` plugin which reads customizations from files, associated with classes or fields. For instance, `org\jvnet\jaxb2_commons\tests\issues\Gh24Type.value.xml` customizes the `value` property of the `org.jvnet.jaxb2_commons.tests.issues.Gh24Type` class.

So how it works:

* Include `jaxb2-basics`
* Enable `-Xcustomizations` plugin and point `-Xcustomizations-directory=<dir>` to whatever directory you want to load customizations files from. For instance, `${basedir}/src/main/resources`.
* Create a file named after the class and/or property you want to customize. For instance for the `value` property of the `org.jvnet.jaxb2_commons.tests.issues.Gh24Type` class you'll have the `src/main/resources/org/jvnet/jaxb2_commons/tests/issues/Gh24Type.value.xml` file.
* Put your customizations into this file. Must be valid XML, for instance:

```
<annox:annotate xmlns:annox="http://annox.dev.java.net">@org.eclipse.persistence.oxm.annotations.XmlCDATA</annox:annotate>
```

See [this project](https://github.com/highsource/jaxb2-annotate-plugin/tree/master/tests/issues), especially `Gh24Type` for example.

The new plugin is not released yet so you'll have to build things first (`jaxb2-basics` and `jaxb2-annotate plugin`).

Hope this helps.

**Comment by lau-sch** [comment]
@highsource Thanks for the recent release. This issue was targeted for 1.0.3, but it is apparently still not fixed. Is a future fix viable or this suggestion above is still the only way?

**Comment by highsource** [comment]
@lau-sch I've checked it again. It is fixed. See [this test project](https://github.com/highsource/jaxb2-annotate-plugin/tree/master/tests/issues).

As described above, you'll need the `customzations` plugin to attach customization to the `value` field. I know no better way at the moment.
