### ISSUE TITLE
Provider org.jvnet.jaxb2_commons.plugin.tostring.ToStringPlugin could not be instantiated

### ISSUE THREAD

**Issue by fbonic** [highsource/jaxb2-annotate-plugin#25]
I have downloaded the project jaxb2-annotate-plugin and I try to execute the "generate-source" task but I have the following error:

```
Buildfile: C:\moxy\project\jaxb2-annotate-plugin-master\samples\annotate\project-build.xml
generate-sources:

BUILD FAILED
C:\moxy\project\jaxb2-annotate-plugin-master\samples\annotate\project-build.xml:91: java.util.ServiceConfigurationError: com.sun.tools.xjc.Plugin: Provider org.jvnet.jaxb2_commons.plugin.tostring.ToStringPlugin could not be instantiated

Total time: 521 milliseconds

```

Here is the content of lib directory:
- activation-10.3.jar
- annox-0.5.1.jar
- commons-beanutils-1.8.3.jar
- commons-lang3-3.1.jar
- commons-logging-1.3.jar
- hibernate-search-3.4.0.Final.jar
- javaparser-1.0.10.jar
- jaxb-api-2.2.jar
- jaxb-impl-2.2.6.jar
- jaxb-xjc-2.2.jar
- jaxb2-basics-0.6.0.jar
- jaxb2-basics-annotate-1.0.2.jar
- jaxb2-basics-ant-0.6.0.jar
- jaxb2-basics-jaxb-xjc-2.2.4-1.jar
- jaxb2-basics-tools-0.6.0.jar
- jsr173_api.jar
- stax-api-1.0-2.jar

Maybe some libs are missing or unnecessary?
Regards,

**Comment by highsource** [comment]
Where did you get this version? Version 0.6.0 is pretty old for jaxb2-basics, current is 0.11.0.

**Comment by fbonic** [comment]
I have taken the first result on http://mvnrepository.com without look if there was a newer version.
With the jaxb2-basics-0.11.0.jar the result is the same :(

**Comment by highsource** [comment]
I wonder how you get the sample project. It is not distributed at the moment. `project-build.xml` and `project-pom.xml` are not intended to be executed, they are used when building sample.

So first you have to `mvn clean install -Pall`, then you'll get a couple of ZIP files generated under `samples/annotat/target/`. There's one for Ant and one for Maven. Unzip and then you can run `ant` or `mvn clean install` on them.

**Comment by fbonic** [comment]
I have found the sample project in a comment on stackOverflow (http://stackoverflow.com/questions/33525642/how-to-use-jaxb2-annotate-plugin-with-xjc-in-command-line).

When I run mvn clean install -Pall, it fails :

[ERROR] Failed to execute goal on project jaxb2-basics-annotate: Could not resolve dependencies for project org.jvnet.jaxb2_commons:jaxb2-basics-annotate:jar:1.0.3-SNAPSHOT: Failure to find org.jvnet.jaxb2_commons:jaxb2-basics-tools:jar:0.11.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the updateinterval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help1]

De : Alexey Valikov [mailto:notifications@github.com]
Envoyé : mardi 22 mars 2016 16:25
À : highsource/jaxb2-annotate-plugin <jaxb2-annotate-plugin@noreply.github.com>
Cc : Fabien BONIC <fabien.bonic@kurmi-software.com>
Objet : Re: [jaxb2-annotate-plugin] Provider org.jvnet.jaxb2_commons.plugin.tostring.ToStringPlugin could not be instantiated (#25)


I wonder how you get the sample project. It is not distributed at the moment. project-build.xml and project-pom.xml are not intended to be executed, they are used when building sample.

So first you have to mvn clean install -Pall, then you'll get a couple of ZIP files generated under samples/annotat/target/. There's one for Ant and one for Maven. Unzip and then you can run ant or mvn clean install on them.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/highsource/jaxb2-annotate-plugin/issues/25#issuecomment-199863871>

C:\project\jaxb2-annotate-plugin-master>mvn clean install -Pall
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-sample-annotate:pom:1.0.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-invoker-plugin is missing. @ org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-sample-annotate:[unknown-version], C:\project\jaxb2-annotate-plugin-master\samples\annotate\pom.xml, line 105, column 12
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-samples:pom:1.0.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-invoker-plugin is missing. @ org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-samples:[unknown-version], C:\project\jaxb2-annotate-plugin-master\samples\pom.xml, line 129, column 12
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-test-annotate:jar:1.0.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.jvnet.jaxb2.maven2:maven-jaxb2-plugin is missing. @ org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-test-annotate:[unknown-version], C:\project\jaxb2-annotate-plugin-master\tests\annotate\pom.xml, line 58, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-test-annox-schema:jar:1.0.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.jvnet.jaxb2.maven2:maven-jaxb2-plugin is missing. @ org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-test-annox-schema:[unknown-version], C:\project\jaxb2-annotate-plugin-master\tests\annox\schema\pom.xml, line 54, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-issues:jar:1.0.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.jvnet.jaxb2.maven2:maven-jaxb2-plugin is missing. @ org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-issues:[unknown-version], C:\project\jaxb2-annotate-plugin-master\tests\issues\pom.xml, line 58, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-test-one:jar:1.0.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.jvnet.jaxb2.maven2:maven-jaxb2-plugin is missing. @ org.jvnet.jaxb2_commons:jaxb2-annotate-plugin-test-one:[unknown-version], C:\project\jaxb2-annotate-plugin-master\tests\one\pom.xml, line 57, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] JAXB2 Annotate Plugin Project
[INFO] JAXB2 Annotate Plugin
[INFO] JAXB2 Annotate Plugin - Samples
[INFO] JAXB2 Annotate Plugin - Sample [annotate]
[INFO] JAXB2 Annotate Plugin - Tests
[INFO] JAXB2 Annotate Plugin - Test [annotate]
[INFO] JAXB2 Annotate Plugin - Test [annox]
[INFO] JAXB2 Annotate Plugin - Test [annox-annotations]
[INFO] JAXB2 Annotate Plugin - Test [annox-schema]
[INFO] JAXB2 Annotate Plugin - Test [issues]
[INFO] JAXB2 Annotate Plugin - Test [one]
[INFO] JAXB2 Annotate Plugin - Test [jaxws]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JAXB2 Annotate Plugin Project 1.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jaxb2-annotate-plugin-project ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ jaxb2-annotate-plugin-project ---
[INFO]
[INFO] --- license-maven-plugin:2.11:check (license-checkheaders) @ jaxb2-annotate-plugin-project ---
[INFO] Checking licenses...
[INFO]
[INFO] >>> maven-source-plugin:2.3:jar (attach-source) > generate-sources @ jaxb2-annotate-plugin-project >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ jaxb2-annotate-plugin-project ---
[INFO]
[INFO] <<< maven-source-plugin:2.3:jar (attach-source) < generate-sources @ jaxb2-annotate-plugin-project <<<
[INFO]
[INFO] --- maven-source-plugin:2.3:jar (attach-source) @ jaxb2-annotate-plugin-project ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jaxb2-annotate-plugin-project ---
[INFO] Installing C:\project\jaxb2-annotate-plugin-master\pom.xml to C:\Users\Fabien BONIC\.m2\repository\org\jvnet\jaxb2_commons\jaxb2-annotate-plugin-project\1.0.3-SNAPSHOT\jaxb2-annotate-plugin-project-1.0.3-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JAXB2 Annotate Plugin 1.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jvnet.jaxb2_commons:jaxb2-basics-tools:jar:0.11.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JAXB2 Annotate Plugin Project ...................... SUCCESS [  3.241 s]
[INFO] JAXB2 Annotate Plugin .............................. FAILURE [  0.812 s]
[INFO] JAXB2 Annotate Plugin - Samples .................... SKIPPED
[INFO] JAXB2 Annotate Plugin - Sample [annotate] .......... SKIPPED
[INFO] JAXB2 Annotate Plugin - Tests ...................... SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [annotate] ............ SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [annox] ............... SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [annox-annotations] ... SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [annox-schema] ........ SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [issues] .............. SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [one] ................. SKIPPED
[INFO] JAXB2 Annotate Plugin - Test [jaxws] ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.268 s
[INFO] Finished at: 2016-03-23T11:14:06+01:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jaxb2-basics-annotate: Could not resolve dependencies for project org.jvnet.jaxb2_commons:jaxb2-basics-annotate:jar:1.0.3-SNAPSHOT: Failure to find org.jvnet.jaxb2_commons:jaxb2-basics-tools:jar:0.11.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the updateinterval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :jaxb2-basics-annotate

**Comment by highsource** [comment]
I'm closing this as it is most probably obsolete and addressed in a wrong project anyway.

If the issue still persists, please open a new issue in JAXB2 Basics.
