### ISSUE TITLE
Support to remove annotations

### ISSUE THREAD

**Issue by MiErnst** [highsource/jaxb2-annotate-plugin#26]
Hi,
I would like to work with the XmlValue annotation as suggested by [6.2.7.4 Mapping a Class to Simple Content or Simple Type: XmlValue](https://jaxb.java.net/tutorial/section_6_2_7_4-Mapping-a-Class-to-Simple-Content-or-Simple-Type-XmlValue.html). As just adding the annotation is not possible as `XmlElement` and `XmlValue` are mutually exclusive. A support to remove annotations would be nice similar to the suggested solution from issue #8.

```
<annox:remove-annotation class="javax.xml.bind.XmlElement"/>
```

**Comment by highsource** [comment]
Would be a good feature. Open for PRs. :)

**Comment by bgedik** [comment]
This would help me a lot as well.

**Comment by kishor-p** [comment]
Could it be possible to know when or which version this can be expected?

**Comment by highsource** [comment]
@MiErnst @bgedik @kishor-p I have implemented this. Please checkout, build and try it out before I release this.

**Comment by bgedik** [comment]
@highsource I can give this a try tomorrow.

**Comment by kevemueller** [comment]
I have just compiled SNAPSHOT and can confirm that it removes annotations as expected.

I have a side-effect, though. I would like to remove (@XmlElement) and re-apply it differently. I use
jaxb:bindings, first annox:removeAnnotation, then annox:annotate. Unfortunately the annox:annotate does not seem to make it, the result is a removed annotation.

**Comment by highsource** [comment]
> I have a side-effect, though. I would like to remove (`@XmlElement`) and re-apply it differently. I use
`jaxb:bindings`, first `annox:removeAnnotation`, then `annox:annotate`. Unfortunately the `annox:annotate` does not seem to make it, the result is a removed annotation.

You don't need to remove and annotate again. Just annotate with `@XmlElement` as you want it. Existing annotation should be overridden.

**Comment by kevemueller** [comment]
Perfect. The plugin just works fine. 
Will you release it soon? Currently this feature is in SNAPSHOT only.

**Comment by highsource** [comment]
@kevemueller Yes, I'm working on a release right now. It's not quite trivial as it requires moving to JAXB 2.3.0 and Java 9.

**Comment by highsource** [comment]
https://github.com/highsource/jaxb2-annotate-plugin/releases/tag/1.1.0

**Comment by krishnanunnijs** [comment]
@highsource  That saved my day.. AWESOME :) Cheers !

**Comment by MiErnst** [comment]
Thanks for fixing. 👍
