### ISSUE TITLE
How can I add annotation in xjc path?

### ISSUE THREAD

**Issue by cHullaert** [highsource/jaxb2-annotate-plugin#30]
I want to annotate class with spring annotation.

**Comment by highsource** [comment]
See [Ant](https://github.com/highsource/jaxb2-annotate-plugin/blob/master/samples/annotate/project-build.xml) or [Maven](https://github.com/highsource/jaxb2-annotate-plugin/blob/master/samples/annotate/project-pom.xml) samples or use [`xjc -classpath`](https://jaxb.java.net/2.2.4/docs/xjc.html).

**Comment by cHullaert** [comment]
You saved my day. 
Some heroes don't have a cloak, He's called "highsource"

thx ^^

**Comment by highsource** [comment]
No problem. Have a nice day. :)
