### ISSUE TITLE
annox:annotate + annox:class does not work for class annotation

### ISSUE THREAD

**Issue by dmak** [highsource/jaxb2-annotate-plugin#31]
Perhaps I missed something, but I found out that `<annox:annotate annox:class ...>` does not annotate the class, while the equivalent `<annox:annotate>@...` works just fine. Here is the test example:

```
<xsd:schema xmlns:bar="http://www.foo.org/bar"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
            xmlns:annox="http://annox.dev.java.net"
            targetNamespace="http://www.foo.org/bar"
            jaxb:extensionBindingPrefixes="annox"
            jaxb:version="2.1">

    <xsd:element name="unit" type="bar:unit"/>

    <xsd:complexType name="unit">
        <xsd:annotation>
            <xsd:appinfo>
                <!-- Works fine: -->
                <!-- annox:annotate>@javax.xml.bind.annotation.XmlRootElement(name="unit")</annox:annotate -->
                <!-- Does not work: -->
                <annox:annotate annox:class="javax.xml.bind.annotation.XmlRootElement" name="unit"/>

            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="indicator" type="xsd:string" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>
```

Expected that `org.foo.bar.Unit` is correctly annotated with `@XmlRootElement` in either case.

**Comment by ashokkhetan** [comment]
It's a very old question, but in case it helps someone else.

Try using:
`<annox:annotate>
      <annox:annotate annox:class="javax.xml.bind.annotation.XmlRootElement" name="unit"/>
</annox:annotate>`

**Comment by hamza-zag** [comment]
this work fro me:
  <jaxb:bindings node=".//xs:complexType[@name='element']">
            <annox:annotateClass>@javax.xml.bind.annotation.XmlRootElement(name="ClassName")</annox:annotateClass>
        </jaxb:bindings>

**Comment by laurentschoelens** [comment]
Hi @dmak
I confirm that solution made by @ashokkhetan is working with inlined xsd annotation.
```xml
  <annox:annotate>
    <annox:annotate annox:class="javax.xml.bind.annotation.XmlRootElement" name="unit"/>
  </annox:annotate>
```

Documentation has been restored [here](https://github.com/highsource/jaxb-tools/wiki/JAXB-Annotate-Home#defining-annotations-directly-in-schemas) too for specifying annotations in XSD

You can also specify the annotation this way, since you annotate in the XSD schema, and by adding the following namespace to your `<xs:schema>` root tag `xmlns:ja="http://annox.dev.java.net/javax.xml.bind.annotation"` :
```xml
  <annox:annotate>
    <ja:XmlRootElement name="unit"/>
  </annox:annotate>
```

Regards
