### ISSUE TITLE
annox:annotateClass works only when jaxb:class is provided.

### ISSUE THREAD

**Issue by ulaBLUE** [highsource/jaxb2-annotate-plugin#32]
Hi,
I'm using `annox:annotateClass` feature using `jaxb2-basics-annotate` configured in the `maven-jaxb22-plugin`.  I see that class is not annotated as specified by the bindings unless I also specify `jxb:class' name for it. 

Is that supposed to work like that. As soon as I remove the `jxb:class` the classes are not annotated.

```
	<jxb:bindings schemaLocation="data.xsd">
		<jxb:bindings node="//xsd:element[@name='data']">
			<jxb:class name="Data" />
		</jxb:bindings>
	</jxb:bindings>

	<jxb:bindings schemaLocation="data.xsd">
		<jxb:bindings node="//xsd:element[@name='data']">
			<annox:annotateClass>@com.fasterxml.jackson.annotation.JsonInclude(Include.NON_NULL)
			</annox:annotateClass>
		</jxb:bindings>
	</jxb:bindings>
```

**Comment by highsource** [comment]
If you omit 'jaxb:class`, is the class for `data` generated at all?

JAXB does not always generate classes for top-level elements. `jaxb:class` forces this. So I guess if you omit 'jaxb:class', JAXB just does not generate the class for `data` so there's nothing to annotate.

If this is not the case, please provide the minimal reproducing example.

**Comment by ulaBLUE** [comment]
Thanks for the reponse. The classes are generated normally without the `jaxb:class`. Infact I wouldn't need it until I tried to `annox:annotateClass`. where to upload the example ?

**Comment by highsource** [comment]
Please send me a PR unter https://github.com/highsource/jaxb2-annotate-plugin/tree/master/tests/issue32

**Comment by ulaBLUE** [comment]
Interestingly , this works!
which means if the xpath resolves to complex types @XmlType then it is annotated properly, where as if xpath resolves to an element, it expects jaxb:class.

I shall close this issue but can we interpret something from above findings ?

```
    <jxb:bindings schemaLocation="data.xsd">
        <jxb:bindings node="//xsd:element[@name='data']/xsd:complexType">
            <annox:annotateClass>@com.fasterxml.jackson.annotation.JsonInclude(Include.NON_NULL)
            </annox:annotateClass>
        </jxb:bindings>
    </jxb:bindings>


```

**Comment by highsource** [comment]
I think this works as designed.
