### ISSUE TITLE
Primitive types are not handled correctly

### ISSUE THREAD

**Issue by diegonc** [highsource/jaxb2-annotate-plugin#37]
Hello

I'm trying to attach some `XmlJavaTypeAdapter` annotations to the package-info file using the following bindings (external):

```xml
<jaxb:bindings node="xs:element[@name='lote_comprobantes']/xs:complexType">
  <annox:annotate target="package">
    @javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters(value = {
      @javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(type = double.class, value = my.adapters.TwoDecimalsDoubleAdapter.class)
     ,@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(type = Double.class, value = my.adapters.TwoDecimalsDoubleAdapter.class)
     })
  </annox:annotate>
</jaxb:bindings>
```

However, it's failing with the message `Error parsing annotation. double is a primitive`.
I've traced the exception to the following method in `AnnotatingSingleValueVisitor`.

```java
public JAnnotationUse visit(XClassAnnotationValue<?> value) {
    final JType type = this.codeModel.ref(value.getValue());
    return annotationUse.param(this.name, type);
}
```

The problem seems to be the `ref` method because as it says in the JavaDocs it doesn't handle primitive types.

Luckily, the JCodeModel class offers an alternative method that does handle primitives called `_ref`.

If AnnotatingSingleValueVisitor switches to using _ref primitives' classes could be supported in annotation values.

**Comment by diegonc** [comment]
Oh, it seems that is not enough 😞 While the exception goes away, JAnnotationUse will box the primitive:

```java
/**
 * Adds a member value pair to this annotation based on the
 * type represented by the given JType
 *
 * @param name The simple name for this annotation param
 * @param type the JType representing the actual type
 * @return The JAnnotationUse. More member value pairs can
 *         be added to it using the same or the overloaded methods.
 */
public JAnnotationUse param(String name, JType type){
    JClass c = type.boxify();
    addValue(name, new JAnnotationStringValue ( c.dotclass() ));
    return this;
}
```

There doesn't seem to be an easy way out, too many private and package scoped methods.

**Comment by diegonc** [comment]
Ok, I was looking at the wrong types! Here's an implementation of the visit method that supports primitive types (and works just as before for everything else)

```java
public JAnnotationUse visit(XClassAnnotationValue<?> value) {
    final JType type = this.codeModel._ref(value.getValue());
    if (type.isPrimitive()) {
        /* This is an implementation of JExpr::dotClass
         * for primitive types.
         */
        JExpression expr = new JExpressionImpl() {
            public void generate(JFormatter f) {
                f.g(type).p(".class");
            }
        };
       return annotationUse.param(this.name, expr);
    } else return annotationUse.param(this.name, type);
}
```

With this changes the annotations for the bindings I posted before are being generated correctly.
If you want, I can work on putting all this in a proper pull request.

**Comment by highsource** [comment]
Indeed.

Would you like to make a pull request for this? Code change is fine, we'd just need a few tests.

**Comment by diegonc** [comment]
Sure, let me setup a fork

**Comment by diegonc** [comment]
Is that the correct way to do the tests? i.e. in plugins/src/test/java...? I don't seem to be able to run it

**Comment by highsource** [comment]
Must be fixed now, please check if this works for you.

**Comment by diegonc** [comment]
Yes, it works. Thanks!
