### ISSUE TITLE
Unknown lifecycle phase "annotate"

### ISSUE THREAD

**Issue by welterw8** [highsource/jaxb2-annotate-plugin#38]
[FileProcessor.zip](https://github.com/highsource/jaxb2-annotate-plugin/files/879088/FileProcessor.zip)

hi i've attached my entire (and failing) Maven simple project.

I believe I have followed the instructions in the README.md on:-
https://github.com/highsource/jaxb2-annotate-plugin

and in this file...
	main/resources/import.xsd
.... I've intended to generate @java.lang.Deprecated somewhere by adding this to it...
	<xs:element name="SecurityExecution" type="securityExecution"
		minOccurs="0" maxOccurs="unbounded">
		<xs:annotation>
			<xs:appinfo>
			
			<annox:annotate target="class">@java.lang.Deprecated</annox:annotate>
		</xs:appinfo>
	</xs:annotation>

when i run this...
	mvn clean install -Xannotate -l mvn.log
i get the result you can see in the log file.

Where am i going wrong? 
Thanks!

**Comment by highsource** [comment]
> when i run this...
> mvn clean install -Xannotate -l mvn.log

See https://github.com/highsource/jaxb2-annotate-plugin#using-jaxb2-annotate-plugin-with-maven

In your pom you have `annotate` arg, not `-Xannotate`. And don't do `mvn clean install -Xannotate`, it's just ´mvn clean install`.

**Comment by rickilambert** [comment]
Hi there

even with the -Xannotate i get no failure - for example (just taking a cut of my attempt using the project posted)

```
<xs:element name="Security">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Type" type="xs:string">
							<xs:annotation>
								<xs:appinfo>
									<annox:annotate>ddddedd
									</annox:annotate>
								</xs:appinfo>
							</xs:annotation>
						</xs:element>


```
You would expect this to fail the mvn clean install? Even if i provide a valid @java.lang.SuppressWarnings({"unchecked","rawtypes"}) i get no error at all and no annotation added.
Any ideas?
Thanks

**Comment by highsource** [comment]
Invalid annotation should probably fail.
Please PR your test project under https://github.com/highsource/jaxb2-annotate-plugin-support/f/fileprocessor, I'll take a look.

**Comment by rickilambert** [comment]
Hi

Sorry, i do not understand your instructions so i have posted it as a zip - i hope that is ok

[FileProcessor.zip](https://github.com/highsource/jaxb2-annotate-plugin/files/881961/FileProcessor.zip)

**Comment by highsource** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by rickilambert** [comment]
embarrassingly I am struggling with this - seems to be taking me longer to figure out how to use git than it would be to debug the plugin i think!  is there any easier alternative for me to provide this solution that i have?

thanks for your time

**Comment by highsource** [comment]
Well, it is really worth to learn pull requests, it is one of the most important ways to collaborate in OS projects.
Anyway, I've committed your project:
https://github.com/highsource/jaxb2-annotate-plugin-support/tree/master/f/FileProcessor

**Comment by highsource** [comment]
* Why do you have both `jaxb2-maven-plugin` and `maven-jaxb2-plugin`? I've commented `jaxb2-maven-plugin` out.
* `maven-jaxb2-plugin` actually was not enabled, you need to add an execution.
* After I've enabled it I've found out thet your `pom.xml` was not correct: `version` missing for `jaxb2-annotate-plugin`. Also `FileProcessor` artifact is not available.
* After I've added version and removed the artifact, I also had to add `jaxb:extensionBindingPrefixes="annox"`
* Now I'm getting "Error parsing annotation" as expected. Build fails.
* Replaced `dddd...`  with `@java.lang.SuppressWarnings({"unchecked","rawtypes"})`. Code is generated fine, `@SuppressWarnings` is also in place. Does not compiles, wrong package.
* Added `<generatePackage>com.salerio.idm.system.oms.jaxb.imp</generatePackage>`. Build succeeds now.

**Comment by highsource** [comment]
Here's a commit with all the changes:

https://github.com/highsource/jaxb2-annotate-plugin-support/commit/8ab355beff189751f3aa9071941ddb8f5359787c
