### ISSUE TITLE
jaxb2-basics.version does not exist anymore

### ISSUE THREAD

**Issue by Martin-Wegner** [highsource/jaxb2-annotate-plugin#42]
Since 1.0.3:

The pom.xml contains `<jaxb2-basics.version>0.11.1-SNAPSHOT</jaxb2-basics.version>` but there is only 0.11.1 in the Maven repository. The version 0.11.1-SNAPSHOT does not exist therefore everything is broken.

For example:

![image](https://user-images.githubusercontent.com/8995517/29712350-b152e5dc-8999-11e7-90fc-da8e46e7b8ef.png)

**Comment by Martin-Wegner** [comment]
@highsource you created and released the 1.0.4 version which fixed this issue but you don't published it to the Maven central repository, why?

**Comment by highsource** [comment]
@Martin-Wegner Should be released to Maven Central now, will appear there in a few hours.
