### ISSUE TITLE
Issue with the annox:annotate customization. 

### ISSUE THREAD

**Issue by teo89** [highsource/jaxb2-annotate-plugin#46]
I tried to change annotation for a field with annotation @XMLElement 
Maven plugin was configured as following
`<plugin>
							<groupId>org.jvnet.jaxb2.maven2</groupId>
							<artifactId>maven-jaxb2-plugin</artifactId>
							<version>${maven.jaxb2.plugin}</version>
							<executions>
								<execution>
									<goals>
										<goal>generate</goal>
									</goals>
									<configuration>
										<extension>true</extension>
										<args>
											<args>-Xannotate</args>
										</args>
										<plugins>
											<plugin>
												<groupId>org.jvnet.jaxb2_commons</groupId>
												<artifactId>jaxb2-basics-annotate</artifactId>
												<version>1.0.4</version>
											</plugin>
										</plugins>
										<schemaDirectory>src/main/resources/schema</schemaDirectory>
										<generateDirectory>src/main/java</generateDirectory>
										<bindingDirectory>src/main/resources/bindings</bindingDirectory>
										<useActiveProxyAsHttpproxy>true</useActiveProxyAsHttpproxy>
									</configuration>
								</execution>
							</executions>
						</plugin>`

In my bindings.xjc file added the following bind for my field

`
<jaxb:bindings schemaLocation="http://schemasUrl/example.xsd">
		<jaxb:bindings node="//xs:element[@name='result']">
			<annox:annotate target="field">
				<annox:annotate annox:class="javax.xml.bind.annotation.XmlElements"
					value="false">
					<annox:annotate annox:field="value">
						<annox:annotate annox:class="javax.xml.bind.annotation.XmlElement"
							type="Child" name="child1" />
						<annox:annotate annox:class="javax.xml.bind.annotation.XmlElement"
							type="Child2" name="child2" />
					</annox:annotate>
				</annox:annotate>
			</annox:annotate>
		</jaxb:bindings>
	</jaxb:bindings>
`
But I am keep getting the following error 

`compiler was unable to honor this annox:annotate customization. It is attached to a wrong place, or its inconsistent with other bindings.`

I don't have other bindings. I am trying to understand the plugin but I didn't manage to find any solution.

**Comment by highsource** [comment]
Please post the full `bindings.xjb`.

**Comment by teo89** [comment]
I don't known, if that is an issue or not, but when I started XPath from the 'complexType' element the "annox:annotate" worked.
I have changed the 
`node="//xs:element[@name='result']`

to 

`node="//xs:complexType[@name='complex_Type_Element']/xs:complexContent/xs:extension[@base='base_Type_element']/xs:sequence/[@name='result']`

It was a little bit confusing that for me.
