### ISSUE TITLE
Annotate xsd:any element

### ISSUE THREAD

**Issue by GunoH** [highsource/jaxb2-annotate-plugin#48]
Hi there,

I'm trying to add an annotation to an `xsd:any` element (which is translated in to `java.util.List<Object>` in Java), but so far I've been unsuccessful; keep getting the error message _"compiler was unable to honor this annotate customization. It is attached to a wrong place, or its inconsistent with other bindings."_

So what I want is to add an extra annotation to the _content_ field in the generated class:
```java
public class List {

    @XmlMixed
    @XmlAnyElement(lax = true)
    @javax.xml.bind.annotation.XmlAnyElement(...) // <-- I want this annotation to be added.
    protected java.util.List<Object> content;
[...]
}
```

Is an annotation at this level even supported?
Or am I doing something wrong here?

My schema:
```xml
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
        jaxb:version="2.1"
        elementFormDefault="qualified">

    <xsd:complexType name="List" mixed="true">
        <xsd:sequence>
            <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>
```

Binding file (using `@Deprecated` annotation for simplicity here):
```xml
<jaxb:bindings
        xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:annox="http://annox.dev.java.net"
        jaxb:extensionBindingPrefixes="annox"
        jaxb:version="2.1">

    jaxb:extensionBindingPrefixes="annox"

    <jaxb:bindings schemaLocation="schema.xsd" node="/xsd:schema">
        <jaxb:bindings node="xsd:complexType[@name='List']/xsd:sequence/xsd:any">
            <annox:annotate>@java.lang.Deprecated</annox:annotate>
        </jaxb:bindings>
    </jaxb:bindings>

</jaxb:bindings>
```

Using jaxb2-basics-annotate v1.1.0.

Thanks,
Guno

**Comment by highsource** [comment]
Yes, this is possible but not quite straightforward.

Please create a reproducing project here: https://github.com/highsource/jaxb2-annotate-plugin-support as `a/any`. I will take care of the customizations.

**Comment by highsource** [comment]
Please see the commits.

In some cases XJC doe snot correctly associate customizations with target elemenents. Don't ask me why. :)

For these cases I've developed a "customizations plugin" which reads XML from specified directory and associates them with corresponding elements. So `generated/List.context.xml` will be associated with the `content` property of the `generated.List` class.

**Comment by GunoH** [comment]
Thanks!

Should this also work with the _jaxws-maven-plugin_, with `xjcArg` instead of `arg`?

**Comment by highsource** [comment]
Theoretically jaxb2-annotate-plugin is not dependend on the Maven plugin you use. Practically I get any XJC plugin to run with jaxws-maven-plugin under Java 9+, last time I tried.

**Comment by GunoH** [comment]
Got it to add the annotation now with _jaxws-maven-plugin_ as well, thanks!

There's still an issue though when adding the `XmlAnyElement` annotation; it adds it to the `getContent` method, while there already is such an annotation present at the `content` field itself:

```java
    @XmlAnyElement(<my own parameters>)
    public java.util.List<Object> getContent() {
    [...]
    }
```
```java
    @XmlMixed
    @XmlAnyElement(lax = true)
    protected java.util.List<Object> content;
```

This of course gives trouble when using the generated class at runtime:

```
[Exception [EclipseLink-50072] (Eclipse Persistence Services - 2.6.0.v20150210-f44015d): org.eclipse.persistence.exceptions.JAXBException
Exception Description: Duplicate Property named [content] found on class [generated.List]]
```

What I would like is somehow replace the annotation at the  field (or just remove it and put my own annnotation at the getter method). Is that possible?

**Comment by highsource** [comment]
You can use `target` attribute to specify where to place the annotation.

```xml
<annox:annotate xmlns:annox="http://annox.dev.java.net" target="field">
	@javax.xml.bind.annotation.XmlAnyElement(lax = false)
</annox:annotate>
```

https://github.com/highsource/jaxb2-annotate-plugin-support/commit/ccc172949111d6d242b6ce0036e1f1f334672270

**Comment by GunoH** [comment]
Exactly what I needed. Great!
