### ISSUE TITLE
Incorrect handling of mixed="true" in schema

### ISSUE THREAD

**Issue by ashokkhetan** [highsource/jaxb2-annotate-plugin#51]
If a schema type having **mixed="true"** is annotated with a custom **@XmlType** name, the plugin adds an extra @XmlType annotation at method level too. Is there already a fix for this issue? I am using the old xml syntax in the binding file.

I have attached the sample project here, please refer to ''\annox_sample\target\generated-sources\xjc\generated\LocalType.java', line 54 having the following code:

`@XmlType(name = "Local_Type_New", propOrder = {})`
` public String getContent() {
        return content;
    }`
[annox_sample.zip](https://github.com/highsource/jaxb2-annotate-plugin/files/2657950/annox_sample.zip)

On a separate note, I am using the old xml syntax in the binding file as I am unable to get the new java syntax working. I have mentioned all working and not working annox statements in the binding file (**\annox_sample\src\main\resources\binding.xjb**). Could you please indicate what is wrong in my project which makes the new java syntax fail? I get the following error while using `<annox:annotateClass>@javax.xml.bind.annotation.XmlType(name="Local_Type_New")</annox:annotateClass>:`

`[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (default) on project pwsV4_1: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate: java.lang.NoSuchMethodError: japa.parser.JavaParser.parse(Ljava/io/Reader;Z)Ljapa/parser/ast/CompilationUnit;`

**Comment by highsource** [comment]
Can't reproduce the first problem. Tried the following annotations:

1:

```
<annox:annotateClass>@javax.xml.bind.annotation.XmlType(name="Local_Type_New")</annox:annotateClass>
```

2:

```
<annox:annotate target="class">@javax.xml.bind.annotation.XmlType(name="Local_Type_New")</annox:annotate>
```

Both work an only annotate the class with `@XmlType`.

The following two customization predictably don't work:

3:

```
<annox:annotate>@javax.xml.bind.annotation.XmlType(name="Local_Type_New")</annox:annotate>
```

4:

```
<annox:annotate>
	<annox:annotate annox:class="javax.xml.bind.annotation.XmlType" name="Local_Type_New"/>
</annox:annotate>
```

The problem is that XJC attaches customization elements to both the class and the property for mixed complex types.
So you have to specify the target in this case.

**Comment by highsource** [comment]
As for the second problem I could also not reproduce this. You `pom.xml` for some reason included the `com.google.code.javaparser:javaparser:1.0.10` dependency. When I comment it out, it works. Not sure why you put the dependency there in first place, but it broke things.

**Comment by highsource** [comment]
I've added a test case to demonstrate that it's working. This is the actual code produced:

```
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.09 at 02:41:39 PM CET 
//


package org.jvnet.jaxb2_commons.tests.issues;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for gh51Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gh51Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Lan" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gh51TypeNew", propOrder = {
    "content"
})
public class Gh51Type {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "Lan")
    protected String lan;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    public boolean isSetContent() {
        return (this.content!= null);
    }

    /**
     * Gets the value of the lan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLan() {
        return lan;
    }

    /**
     * Sets the value of the lan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLan(String value) {
        this.lan = value;
    }

    public boolean isSetLan() {
        return (this.lan!= null);
    }

}
```

**Comment by ashokkhetan** [comment]
Thanks very much to look into this. I have raised a separate issue #52 for the 'annox:annotateClass' issue.

Regarding the mixed complex types issue, following works good too:

`<annox:annotate target="class">
<annox:annotate annox:class="javax.xml.bind.annotation.XmlType" name="Local_Type_New"/>
</annox:annotate>`

However, I would prefer to use the java syntax for mixed complex types (or, in general) once that gets working.

**Comment by highsource** [comment]
As I wrote, Java syntax works as well:

```
		<jaxb:bindings node="xsd:complexType[@name='gh51Type']">
			<annox:annotateClass>@javax.xml.bind.annotation.XmlType(name="gh51TypeNew")</annox:annotateClass>
		</jaxb:bindings>
```

This is what I have as a test case in `tests/issues` project now.
