### ISSUE TITLE
cant annotate explicit enum

### ISSUE THREAD

**Issue by eiswind** [highsource/jaxb2-annotate-plugin#6]
HI,

I have enums with int values that I need to map individually. I tried to annotate them like
 <jxb:bindings node="//xs:simpleType[@name='List1']">

```
        <annox:annotateClass>@java.lang.SuppressWarnings</annox:annotateClass>
        <jxb:typesafeEnumClass name="List1">

            <jxb:typesafeEnumMember value="01" name="V01">
```

But that doesn't work. How would I annotate the enum members?

**Comment by highsource** [comment]
Please try `annox:annotateEnum`. If not then this is probably a missing feature. Could you please PR a test case in this project:

https://github.com/highsource/jaxb2-annotate-plugin/tree/master/tests/issues

I'll take care of it then.
