### ISSUE TITLE
Link to highsource.org redirects to scam website

### ISSUE THREAD

**Issue by lion7** [highsource/jaxb2-annotate-plugin#64]
In the README there is a link to the Old XML syntax referring to http://confluence.highsource.org/display/J2B/Annotate+Plugin.
Currently this link (and any other link to highsource.org) redirects me to random scam websites. Looks like the webserver is compromised 😢

**Comment by perlun** [comment]
For the reference, this still seems to be an issue. :grimacing:

**Comment by lion7** [comment]
Just wanted to point out that the author of this plugin (and the Maven JAXB plugin) has deceased in January 2021.
See http://good-bye.org/alexey-valikov/ for the remembrance page. 

My assumption is that the domain expired after a while and some evil person claimed the domain to serve the thrash that's now there.. Just a shame really.

**Comment by lion7** [comment]
Keeping this open so it will stay in the top of the issue list.

**Comment by perlun** [comment]
@lion7 Thanks for letting me (and others) know. Really sorry to hear that. :cry: 

Yes, let's keep the issue open so that it's easier for people to find. :+1:

**Comment by laurentschoelens** [comment]
We try to update the maven-jaxb-plugin and I found same issue as yours.
Final goal would be to have everything (maven plugin, jaxb-basics, jaxb-annotate...) in one single repository.
We'll try to keep you updated
I think documentation should point in the end to github wiki pages

**Comment by laurentschoelens** [comment]
@perlun  / @lion7 : I did manage to get the hand on documentation (thanks to web archive)
Wiki has been updated in new annotate-plugin's location (https://github.com/highsource/jaxb-tools)
https://github.com/highsource/jaxb-tools/wiki/Annox-Home
Regards 😄

**Comment by laurentschoelens** [comment]
We also update the readme section in jaxb-tools.
Regards

**Comment by perlun** [comment]
Thanks @laurentschoelens. Will you be able to fix the link in the README in this project as well? It still seems to point at the "bad" site.

**Comment by laurentschoelens** [comment]
Yes. We will update the readme to tell user to go to the new repo location too.
By restoring the documentation in the wiki, I've also learned many things :)

**Comment by laurentschoelens** [comment]
@perlun and @lion7 
Readme updated with note regarding migration to jaxb-tools and fixing link to jaxb-tools wiki to avoid scam redirect

**Comment by laurentschoelens** [comment]
Fixed in https://github.com/highsource/jaxb2-annotate-plugin/commit/1e16849a0ee89f9d921f0164058bbf0a7217d3b2
