### ISSUE TITLE
Package names in bindings files are ignored

### ISSUE THREAD

**Issue by Moortu** [highsource/jaxb2-annotate-plugin#69]
```
resources/
├── bindings/
│      ├── common_a.xjb
│      └── common_b.xjb
└── xsd/
         ├── a/
         │      └── a.xsd
         ├── b/
         │      └── b.xsd
         └── common/
                   └── common.xsd
```

a.xsd :
```
<xsd:schema targetNamespace="http://www.foo.com/schemas/bar/management/input/v1"
			xmlns="http://www.foo.com/schemas/bar/management/input/v1"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:p1="http://www.foo.com/schemas/commonbutamazing/v2"
	<xsd:import namespace="http://www.foo.com/schemas/commonbutamazing/v2" schemaLocation="../common/common.xsd"/>/>
<!-- insert some structure that depends on common.xsd-->
</xsd:schema>
```

b.xsd :
```
<xsd:schema targetNamespace="http://www.foo.com/schemas/bar/responding/output/v3"
			xmlns="http://www.foo.com/schemas/bar/responding/output/v3"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:p1="http://www.foo.com/schemas/commonbutamazing/v2"
	<xsd:import namespace="http://www.foo.com/schemas/commonbutamazing/v2" schemaLocation="../common/common.xsd"/>/>
<!-- insert some structure that depends on common.xsd-->
</xsd:schema>
```

common.xsd :
```
<xsd:schema targetNamespace="http://www.foo.com/schemas/commonbutamazing/v2" 
                      xmlns="http://www.foo.com/schemas/commonbutamazing/v2" 
                      xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!-- some structure -->
</xsd:schema>
```

common_a.xjb:
```
<bindings xmlns="http://java.sun.com/xml/ns/jaxb" version="2.1">
    <bindings schemaLocation="../xsd/a/a.xsd">
        <schemaBindings>
            <package name="com.foo.something.schema.management.input"/>
        </schemaBindings>
   </bindings>
        <bindings schemaLocation="../xsd/common/common.xsd">
            <schemaBindings>
                <package name="com.foo.something.schema.common"/>
            </schemaBindings>
        </bindings>
</bindings>
```

common_b.xjb:
```
<jaxb:bindings
        version="2.1"
        xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:annox="http://annox.dev.java.net"
        jaxb:extensionBindingPrefixes="xjc annox">

    <bindings schemaLocation="../xsd/b/b.xsd">
        <schemaBindings>
            <package name="com.foo.something.schema.responding.output"/>
        </schemaBindings>
        <jaxb:bindings schemaLocation="../xsd/b/b.xsd" node="//xs:element[@name='something']" multiple="true">
            <annox:annotate target="field">@javax.annotation.Nullable</annox:annotate>
        </jaxb:bindings>
        <bindings schemaLocation="../xsd/common/common.xsd">
            <schemaBindings>
                <package name="com.foo.something.schema.common"/>
            </schemaBindings>
        </bindings>
    </bindings>
</jaxb:bindings>
```

```
<plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-xjc-plugin</artifactId>
                <version>${cxf-xjc-plugin.version}</version>
                <configuration>
                    <extensions>
                        <extension>org.jvnet.jaxb2_commons:jaxb2-basics-annotate:${jaxb2-basics-annotate.version}</extension>
                    </extensions>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>xsdtojava</goal>
                        </goals>
                        <configuration>
                            <sourceRoot>${basedir}/target/generated-sources/cxf</sourceRoot>
                            <xsdOptions>
                                <xsdOption>
                                    <xsd>
                                        src/main/resources/xsd/a/a.xsd
                                    </xsd>
                                    <bindingFile>src/main/resources/binding/common_a.xjb</bindingFile>
                                    <extension>true</extension>
                                    <extensionArgs>
                                        <extensionArg>-Xannotate</extensionArg>
                                    </extensionArgs>
                                </xsdOption>
                                <xsdOption>
                                    <xsd>
                                        src/main/resources/xsd/b/b.xsd
                                    </xsd>
                                    <bindingFile>src/main/resources/binding/common_b.xjb</bindingFile>
                                    <extension>true</extension>
                                    <extensionArgs>
                                        <extensionArg>-Xannotate</extensionArg>
                                    </extensionArgs>
                                </xsdOption>
                            </xsdOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

This will produce the following folder structure with corresponding packagenames
```
com/
└── foo/
       ├── something/
       │        └── schema/
       │                ├── management/
       │                │       └── input/ //generated input files
       │                │    
       │                └── common/  //generated common files  
       │
       └── schemas/
                ├── commonbutamazing/
                │      └── v2/ //generated common files (**same at the other common generated files**)
                │
                └──bar/
                         └──responding/
                                     └──output
                                                  └──v3/ generated files
```

------------------------------------------------------------------------------------------------------
Without org.jvnet.jaxb2_commons:jaxb2-basics-annotate
and the jxb:annotate bindings in the common_b.xjb 
It will produce the following with the corresponding packagename

```
com/
└── foo/
       ├── something/
                └── schema/
                        ├── management/
                        │       └── input/ //generated input files
                        │ 
                        ├── responding/
                        │       └── output/ //generated input files
                        │    
                        └── common/  //generated common files  
```

**Comment by laurentschoelens** [comment]
@Kelsinga : sorry for the delay. I tried to reproduce your problem and didn't get the output you mentioned above.

I've created the [branch jap-69](https://github.com/laurentschoelens/jaxb-tools/tree/jap-69) with a [test case](https://github.com/laurentschoelens/jaxb-tools/tree/jap-69/jaxb-annotate-parent/tests/jap-69) following your instructions and the output is like the following :

<img width="340" alt="image" src="https://github.com/highsource/jaxb2-annotate-plugin/assets/61973605/5965baf6-b4f3-4403-a729-8856e9ff05f8">

With plugin configuration being like :

```xml
<plugin>
  <groupId>org.apache.cxf</groupId>
  <artifactId>cxf-xjc-plugin</artifactId>
  <version>4.0.0</version>
  <configuration>
    <extensions>
      <extension>org.jvnet.jaxb:jaxb-plugin-annotate:${project.version}</extension>
    </extensions>
  </configuration>
  <executions>
    <execution>
      <id>generate-sources</id>
      <phase>generate-sources</phase>
      <goals>
        <goal>xsdtojava</goal>
      </goals>
      <configuration>
        <sourceRoot>${basedir}/target/generated-sources/cxf</sourceRoot>
        <xsdOptions>
          <xsdOption>
            <xsd>
              src/main/resources/xsd/a/a.xsd
            </xsd>
            <bindingFile>src/main/resources/bindings/common_a.xjb</bindingFile>
            <extension>true</extension>
            <extensionArgs>
              <extensionArg>-Xannotate</extensionArg>
            </extensionArgs>
          </xsdOption>
          <xsdOption>
            <xsd>
              src/main/resources/xsd/b/b.xsd
            </xsd>
            <bindingFile>src/main/resources/bindings/common_b.xjb</bindingFile>
            <extension>true</extension>
            <extensionArgs>
              <extensionArg>-Xannotate</extensionArg>
            </extensionArgs>
          </xsdOption>
        </xsdOptions>
      </configuration>
    </execution>
  </executions>
</plugin>
```

Could you create a test case that output like your issue ?

**Comment by Kelsinga** [comment]
> @Kelsinga : sorry for the delay. I tried to reproduce your problem and didn't get the output you mentioned above.
> 
> I've created the [branch jap-69](https://github.com/laurentschoelens/jaxb-tools/tree/jap-69) with a [test case](https://github.com/laurentschoelens/jaxb-tools/tree/jap-69/jaxb-annotate-parent/tests/jap-69) following your instructions and the output is like the following :
> 
> <img alt="image" width="340" src="https://private-user-images.githubusercontent.com/61973605/295172808-5965baf6-b4f3-4403-a729-8856e9ff05f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTU4ODMsIm5iZiI6MTcwNDc5NTU4MywicGF0aCI6Ii82MTk3MzYwNS8yOTUxNzI4MDgtNTk2NWJhZjYtYjRmMy00NDAzLWE3MjktODg1NmU5ZmYwNWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwMTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTc0Y2M5YzJhOGRiYmYwNTUzZmVhY2NkNmIxMDBmZTFjZjJiODM4YmYxMTk4OTQ4ZGM3Y2QwNzg4MDU4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3pwqY2Oeqynz1v38Kyg-zl84aOwCL20N6uJ8Ciw4Plc">
> With plugin configuration being like :
> 
> ```
> <plugin>
>   <groupId>org.apache.cxf</groupId>
>   <artifactId>cxf-xjc-plugin</artifactId>
>   <version>4.0.0</version>
>   <configuration>
>     <extensions>
>       <extension>org.jvnet.jaxb:jaxb-plugin-annotate:${project.version}</extension>
>     </extensions>
>   </configuration>
>   <executions>
>     <execution>
>       <id>generate-sources</id>
>       <phase>generate-sources</phase>
>       <goals>
>         <goal>xsdtojava</goal>
>       </goals>
>       <configuration>
>         <sourceRoot>${basedir}/target/generated-sources/cxf</sourceRoot>
>         <xsdOptions>
>           <xsdOption>
>             <xsd>
>               src/main/resources/xsd/a/a.xsd
>             </xsd>
>             <bindingFile>src/main/resources/bindings/common_a.xjb</bindingFile>
>             <extension>true</extension>
>             <extensionArgs>
>               <extensionArg>-Xannotate</extensionArg>
>             </extensionArgs>
>           </xsdOption>
>           <xsdOption>
>             <xsd>
>               src/main/resources/xsd/b/b.xsd
>             </xsd>
>             <bindingFile>src/main/resources/bindings/common_b.xjb</bindingFile>
>             <extension>true</extension>
>             <extensionArgs>
>               <extensionArg>-Xannotate</extensionArg>
>             </extensionArgs>
>           </xsdOption>
>         </xsdOptions>
>       </configuration>
>     </execution>
>   </executions>
> </plugin>
> ```
> 
> Could you create a test case that output like your issue ?

It's been almost 2 years, I don't have this issue anymore 😅

**Comment by laurentschoelens** [comment]
Good to know - what was the issue if you'd fixed it - and if you remember ?

I invite you to look at the [migration guide](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide) to get the latest versions of the plugin (and get compatibility with JAXB-jakarta).

Could you also close the issue ?
I'll merge the test project to check it won't break on future builds.

**Comment by laurentschoelens** [comment]
Closing as non reproduced in new versions
