### ISSUE TITLE
annox:annotate not working on attribute getter or setter

### ISSUE THREAD

**Issue by bertramn** [highsource/jaxb2-annotate-plugin#7]
Hi there,

I have annotated a `xsd:attribute` with a `annox:annotate` targetting the getter but unfortunately the annotation is never added to the generated Java field getter method. When I add the same annotation to an `xsd:element` then it works as expected. I cannot find any examples where a xsd attribute is annotated targetting either getter or setter either. Is this not implemented?

Cheers,
 Niels

Not working attribute:

```xml
<xsd:attribute name="id" type="c:ObjectIDType" use="optional">
  <xsd:annotation>
    <xsd:appinfo>
      <annox:annotate target="getter">@com.wordnik.swagger.annotations.ApiModelProperty(name="customName")</annox:annotate>
      <annox:annotate target="field">@org.jongo.marshall.jackson.oid.Id</annox:annotate>
    </xsd:appinfo>
    <xsd:documentation>The menu reference id</xsd:documentation>
  </xsd:annotation>
</xsd:attribute>
```

Nope

```java
/**
 * Sets the value of the id property.
 * 
 */
public void setId(String value) {
    id = value;
}

public void unsetId() {
    id = null;
}

/**
 * Gets the value of the id property.
 * 
 */
public String getId() {
    return id;
}
```

The same annotation on an `xsd:element`

```xml
<xsd:element name="Name" type="xsd:string">
  <xsd:annotation>
    <xsd:appinfo>
      <annox:annotate target="getter">@com.wordnik.swagger.annotations.ApiModelProperty(name="customName")</annox:annotate>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:element>
```

Yep

```java
/**
 * Gets the value of the name property.
 * 
 * @return
 *     possible object is
 *     {@link String }
 *     
 */
@ApiModelProperty(name = "customName")
public String getName() {
    return name;
}

/**
 * Sets the value of the name property.
 * 
 * @param value
 *     allowed object is
 *     {@link String }
 *     
 */
public void setName(String value) {
    this.name = value;
}
```

**Comment by highsource** [comment]
Could you please post the minimal schema that reproduces this? Ideally a pull request for this schema in the test project:

https://github.com/highsource/jaxb2-annotate-plugin/blob/master/tests/issues/src/main/resources/schema.xsd

**Comment by bertramn** [comment]
Hmm I just experimented a bit and found that the cxf default value plugin is the one that somehow looses the annotations from the field. When I disable the plugin (remove `-Xdv` arg) then it all works well again.

Thank you for the quick reply, much appreciated. Niels

Just for the record I use following version:

```xml
<plugin>
	<groupId>org.jvnet.jaxb2_commons</groupId>
	<artifactId>jaxb2-basics-annotate</artifactId>
	<version>1.0.1</version>
</plugin>
<plugin>
	<groupId>org.apache.cxf.xjcplugins</groupId>
	<artifactId>cxf-xjc-dv</artifactId>
	<version>2.7.0</version>
</plugin>
```

**Comment by highsource** [comment]
Thank you for the report.
