### ISSUE TITLE
 Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed: Index -1 out of bounds for length 0 

### ISSUE THREAD

**Issue by saikatpiramal** [highsource/jaxb2-annotate-plugin#70]
Getting this errror while running mvn command

**Comment by laurentschoelens** [comment]
Hi @saikatpiramal 

Could you provide more context about your error
Also please run with -X mvn option to have more trace of the exception

**Comment by laurentschoelens** [comment]
Closing with no details about problem
